# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: livehd_exporter
    scrape_interval: 2m
    scrape_timeout:  2m
    metrics_path: "/metrics"
    static_configs:
    - targets: ['localhost:8000']


# Alertmanager settings
rule_files:
  - './alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'localhost:9093'
